site_name: Borogove

theme:
  name: readthedocs
  prev_next_buttons_location: false
  include_homepage_in_sidebar: false

plugins:
  - search
  - mkdoxy:
      projects:
        c:
          src-dirs: ./cpp/
          full-doc: true
          doxy-cfg:
            PREDEFINED: API_PREFIX MKDOCS
            OPTIMIZE_FOR_C: true
            JAVADOC_BANNER: true
            JAVADOC_AUTOBRIEF: true
            FILE_PATTERNS: "borogove.h"
            RECURSIVE: false

markdown_extensions:
  - markdown.extensions.md_in_html

nav:
  - README: index.md
  - C:
    - c/index.md
    - API Reference: c/borogove_8h.md
  - JavaScript:
    - js/index.md
    - API Reference: js/borogove.md
  - Swift:
    - SwiftPM: ../src/r/swiftpm/
  - Haxe:
    - API Reference: haxe/
